[tasks.generate-bindings]
command = "bindgen"
args = [
    "./MEDAQLib.h",
    "--default-enum-style", "rust",
    "-o", "./src/bindings.rs",
    "--allowlist-function", ".*",
    "--no-layout-tests",
    "--dynamic-loading", "MEDAQLib"
    "--"
    "-x", "c++"
]
